# 这些规则类型不适合放进 Surge 外部 RULE-SET，需直接复制到 [Rule]。
# 例如 DOMAIN-KEYWORD、DST-PORT、嵌套 RULE-SET 等。
DOMAIN-KEYWORD,afreecatv.com,Proxy
DOMAIN-KEYWORD,mtyy,DIRECT
DOMAIN-KEYWORD,mt,DIRECT
DST-PORT,22,DIRECT
DOMAIN-KEYWORD,seller,DIRECT
DOMAIN-KEYWORD,17qcc.com,DIRECT
DOMAIN-KEYWORD,v6.navy,DIRECT
DOMAIN-KEYWORD,dynv6,DIRECT
DOMAIN-KEYWORD,navy,DIRECT
DOMAIN-KEYWORD,keke1.app,DIRECT,no-resolve
DOMAIN-KEYWORD,iPv6,DIRECT,no-resolve
DOMAIN-KEYWORD,clipber,DIRECT
DOMAIN-KEYWORD,333ys.tv,DIRECT
DOMAIN-KEYWORD,kuku,🇯🇵 日本节点
RULE-SET,adblock,REJECT
