#!/usr/bin/env python3
"""Mirror NobyDa's QX AD_Block_Plus list after deterministic line filtering."""
from __future__ import annotations

import argparse
import hashlib
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "QuantumultX" / "AD_Block_Plus.txt"
UPSTREAM_URL = "https://raw.githubusercontent.com/NobyDa/ND-AD/master/QuantumultX/AD_Block_Plus.txt"
EXCLUDED_SUBSTRING = "spotify"


def fetch_upstream() -> bytes:
    request = urllib.request.Request(
        UPSTREAM_URL,
        headers={"User-Agent": "dinyue-qx-adblock-sync/1.0"},
    )
    with urllib.request.urlopen(request, timeout=120) as response:
        if response.status != 200:
            raise RuntimeError(f"unexpected upstream HTTP status: {response.status}")
        return response.read()


def render(source: bytes) -> tuple[str, int, int, str]:
    text = source.decode("utf-8-sig", "strict")
    source_lines = text.splitlines()
    if not source_lines:
        raise RuntimeError("upstream returned no lines")

    kept_lines = [line.rstrip() for line in source_lines if EXCLUDED_SUBSTRING not in line.casefold()]
    removed_count = len(source_lines) - len(kept_lines)
    if any(EXCLUDED_SUBSTRING in line.casefold() for line in kept_lines):
        raise RuntimeError("filtered output still contains an excluded line")

    source_sha256 = hashlib.sha256(source).hexdigest()
    header = [
        "# Curated mirror of NobyDa/ND-AD QuantumultX AD_Block_Plus.",
        f"# Upstream: {UPSTREAM_URL}",
        "# Upstream license: MIT; full text: LICENSES/NobyDa-ND-AD-MIT.txt",
        "# Generated by scripts/sync_qx_adblock.py; excluded source lines are omitted.",
        f"# Upstream SHA256: {source_sha256}",
        f"# Upstream lines: {len(source_lines)}; omitted lines: {removed_count}",
        "",
    ]
    output = "\n".join(header + kept_lines) + "\n"
    # Keep the published artifact free of the excluded substring as well.
    if EXCLUDED_SUBSTRING in output.casefold():
        raise RuntimeError("published output contains the excluded substring")
    return output, len(source_lines), removed_count, source_sha256


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that the committed artifact matches the current upstream transform",
    )
    args = parser.parse_args()

    output, source_count, removed_count, source_sha256 = render(fetch_upstream())
    if args.check:
        if not OUTPUT.exists():
            raise SystemExit(f"missing generated artifact: {OUTPUT}")
        if OUTPUT.read_text(encoding="utf-8") != output:
            raise SystemExit("generated artifact is stale; run scripts/sync_qx_adblock.py")
        print(
            f"verified {OUTPUT.relative_to(ROOT)}: source_lines={source_count} "
            f"omitted={removed_count} upstream_sha256={source_sha256}"
        )
        return

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output, encoding="utf-8")
    print(
        f"wrote {OUTPUT.relative_to(ROOT)}: source_lines={source_count} "
        f"omitted={removed_count} upstream_sha256={source_sha256}"
    )


if __name__ == "__main__":
    try:
        main()
    except (OSError, UnicodeError, RuntimeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
