#!/usr/bin/env python3
"""Mirror fmz200/wool_scripts Surge blockAds module with Spotify influence removed."""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXCLUDED_SUBSTRING = "spotify"
UPSTREAM_URL = (
    "https://raw.githubusercontent.com/fmz200/wool_scripts/main/Surge/module/blockAds.module"
)
UPSTREAM_NAME = "fmz200/wool_scripts Surge/module/blockAds.module"
LICENSE_NOTICE = "GPL-3.0-or-later; full text: LICENSES/fmz200-wool_scripts-GPL-3.0.txt"
OUTPUT = ROOT / "surge" / "wool_scripts" / "blockAds.sgmodule"
README = ROOT / "surge" / "wool_scripts" / "README.md"
RAW_URL = (
    "https://raw.githubusercontent.com/25175/dinyue/main/surge/wool_scripts/blockAds.sgmodule"
)

SPOTIFY_HOSTNAME_RE = re.compile(
    r"(?:^|,\s*)(?:\*-spclient\.spotify\.com|spclient\.wg\.spotify\.com)(?=,|$)",
    re.IGNORECASE,
)


def fetch_upstream(url: str) -> bytes:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "dinyue-wool-surge-sync/1.0"},
    )
    with urllib.request.urlopen(request, timeout=120) as response:
        if response.status != 200:
            raise RuntimeError(f"unexpected upstream HTTP status: {response.status}")
        return response.read()


def scrub_mitm_hostname_line(line: str) -> str | None:
    """Drop Spotify hostnames from the MITM hostname append line; keep the rest."""
    if not line.lower().startswith("hostname"):
        return line
    cleaned = SPOTIFY_HOSTNAME_RE.sub("", line)
    cleaned = re.sub(r",\s*,", ",", cleaned)
    cleaned = re.sub(r"=\s*,", "= ", cleaned)
    cleaned = re.sub(r",\s*$", "", cleaned).rstrip()
    # If scrubbing removed every hostname value, drop the line.
    if re.search(r"hostname\s*=\s*%APPEND%\s*$", cleaned, re.IGNORECASE):
        return None
    return cleaned


def transform(source: bytes) -> tuple[str, int, int, str]:
    text = source.decode("utf-8-sig", "strict")
    source_lines = text.splitlines()
    if not source_lines:
        raise RuntimeError(f"upstream returned no lines: {UPSTREAM_URL}")

    kept: list[str] = []
    omitted = 0
    for line in source_lines:
        raw = line.rstrip()
        lower = raw.casefold()
        if EXCLUDED_SUBSTRING in lower:
            if lower.lstrip().startswith("hostname"):
                scrubbed = scrub_mitm_hostname_line(raw)
                if scrubbed is None:
                    omitted += 1
                    continue
                if EXCLUDED_SUBSTRING in scrubbed.casefold():
                    raise RuntimeError("MITM hostname scrub left Spotify residue")
                kept.append(scrubbed)
                if scrubbed != raw:
                    omitted += 1
                continue
            omitted += 1
            continue
        kept.append(raw)

    if any(EXCLUDED_SUBSTRING in line.casefold() for line in kept):
        raise RuntimeError("filtered output still contains Spotify")

    source_sha256 = hashlib.sha256(source).hexdigest()
    header = [
        "#!name=Dinyue 广告拦截合集（wool_scripts 清洗版）",
        "#!desc=上游 fmz200/wool_scripts blockAds.module 清洗镜像：已去除会干扰音乐会员解锁的改写/脚本/MITM 主机名。",
        "#!author=fmz200 / dinyue mirror",
        "#!homepage=https://github.com/25175/dinyue",
        f"#!raw-url={RAW_URL}",
        "#!tag=去广告, wool_scripts, dinyue",
        "",
        f"# Curated mirror of {UPSTREAM_NAME}.",
        f"# Upstream: {UPSTREAM_URL}",
        f"# Upstream license: {LICENSE_NOTICE}",
        "# Generated by scripts/sync_wool_surge_module.py; music-unlock conflicting lines/hostnames removed.",
        f"# Upstream SHA256: {source_sha256}",
        f"# Upstream lines: {len(source_lines)}; omitted conflicting units: {omitted}",
        "",
    ]

    # Drop upstream metadata headers that would conflict with dinyue branding,
    # keep body starting at the first section or first non-#! content after blank.
    body_start = 0
    for idx, line in enumerate(kept):
        if line.startswith("#!"):
            body_start = idx + 1
            continue
        if line.strip() == "" and body_start:
            # keep scanning through leading blanks after #! headers
            body_start = idx + 1
            continue
        break
    body = kept[body_start:]
    while body and body[0].strip() == "":
        body.pop(0)

    output = "\n".join(header + body) + "\n"
    if EXCLUDED_SUBSTRING in output.casefold():
        raise RuntimeError("published output contains Spotify")
    for required in ("[Rule]", "[URL Rewrite]", "[Script]", "[MITM]"):
        if required not in output:
            raise RuntimeError(f"missing required module section: {required}")
    return output, len(source_lines), omitted, source_sha256


def render_readme(source_count: int, omitted: int, source_sha256: str) -> str:
    # README may mention the exclusion keyword for operators; the sgmodule artifact must not.
    return f"""# wool_scripts Surge 去广告模块（清洗版）

上游：[{UPSTREAM_NAME}]({UPSTREAM_URL})

本目录为独立镜像，不改动 `surge/generated` / Rabbit-Spec / 自用音乐会员解锁链路。

## Surge 模块订阅

```text
{RAW_URL}
```

## 清洗规则

- 删除所有含排除关键词的改写、Map Local、脚本与注释行
- MITM `hostname` 长行仅剔除冲突主机名，保留其余主机名
- 许可证：{LICENSE_NOTICE}

## 最近一次同步

- Upstream SHA256: `{source_sha256}`
- Upstream lines: `{source_count}`
- Omitted conflicting units: `{omitted}`

本地更新：

```bash
python3 scripts/sync_wool_surge_module.py
python3 scripts/sync_wool_surge_module.py --check
```
"""


def sync(check: bool) -> None:
    output, source_count, omitted, source_sha256 = transform(fetch_upstream(UPSTREAM_URL))
    readme = render_readme(source_count, omitted, source_sha256)
    if check:
        if not OUTPUT.exists():
            raise RuntimeError(f"missing generated artifact: {OUTPUT}")
        if OUTPUT.read_text(encoding="utf-8") != output:
            raise RuntimeError(
                f"generated artifact is stale: {OUTPUT.relative_to(ROOT)}; "
                "run scripts/sync_wool_surge_module.py"
            )
        if not README.exists() or README.read_text(encoding="utf-8") != readme:
            raise RuntimeError(
                f"generated README is stale: {README.relative_to(ROOT)}; "
                "run scripts/sync_wool_surge_module.py"
            )
        action = "verified"
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(output, encoding="utf-8")
        README.write_text(readme, encoding="utf-8")
        action = "wrote"
    print(
        f"{action} {OUTPUT.relative_to(ROOT)}: source_lines={source_count} "
        f"omitted={omitted} upstream_sha256={source_sha256}"
    )
    print(f"{action} {README.relative_to(ROOT)}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that committed artifacts match the current upstream transform",
    )
    args = parser.parse_args()
    sync(args.check)


if __name__ == "__main__":
    try:
        main()
    except (OSError, UnicodeError, RuntimeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
