#!/usr/bin/env python3
"""Mirror selected QX-compatible advertising lists after deterministic filtering."""
from __future__ import annotations

import argparse
import hashlib
import sys
import urllib.request
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXCLUDED_SUBSTRING = "spotify"


@dataclass(frozen=True)
class Mirror:
    output: Path
    upstream_url: str
    upstream_name: str
    license_notice: str


MIRRORS = (
    Mirror(
        output=ROOT / "QuantumultX" / "AD_Block_Plus.txt",
        upstream_url="https://raw.githubusercontent.com/NobyDa/ND-AD/master/QuantumultX/AD_Block_Plus.txt",
        upstream_name="NobyDa/ND-AD QuantumultX AD_Block_Plus",
        license_notice="MIT License; full text: LICENSES/NobyDa-ND-AD-MIT.txt",
    ),
    Mirror(
        output=ROOT / "QuantumultX" / "AdRule.list",
        upstream_url="https://raw.githubusercontent.com/NobyDa/Script/master/Surge/AdRule.list",
        upstream_name="NobyDa/Script Surge AdRule",
        license_notice="GPL-3.0-or-later; full text: LICENSES/NobyDa-Script-GPL-3.0.txt",
    ),
    Mirror(
        output=ROOT / "QuantumultX" / "Advertising.list",
        upstream_url="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list",
        upstream_name="blackmatrix7/ios_rule_script QuantumultX Advertising",
        license_notice="GPL-2.0-or-later; full text: LICENSES/blackmatrix7-ios_rule_script-GPL-2.0.txt",
    ),
)


def fetch_upstream(url: str) -> bytes:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "dinyue-qx-adblock-sync/1.0"},
    )
    with urllib.request.urlopen(request, timeout=120) as response:
        if response.status != 200:
            raise RuntimeError(f"unexpected upstream HTTP status: {response.status}")
        return response.read()


def render(mirror: Mirror, source: bytes) -> tuple[str, int, int, str]:
    text = source.decode("utf-8-sig", "strict")
    source_lines = text.splitlines()
    if not source_lines:
        raise RuntimeError(f"upstream returned no lines: {mirror.upstream_url}")

    kept_lines = [line.rstrip() for line in source_lines if EXCLUDED_SUBSTRING not in line.casefold()]
    removed_count = len(source_lines) - len(kept_lines)
    if any(EXCLUDED_SUBSTRING in line.casefold() for line in kept_lines):
        raise RuntimeError("filtered output still contains an excluded line")

    source_sha256 = hashlib.sha256(source).hexdigest()
    header = [
        f"# Curated mirror of {mirror.upstream_name}.",
        f"# Upstream: {mirror.upstream_url}",
        f"# Upstream license: {mirror.license_notice}",
        "# Generated by scripts/sync_qx_adblock.py; excluded source lines are omitted.",
        f"# Upstream SHA256: {source_sha256}",
        f"# Upstream lines: {len(source_lines)}; omitted lines: {removed_count}",
        "",
    ]
    output = "\n".join(header + kept_lines) + "\n"
    if EXCLUDED_SUBSTRING in output.casefold():
        raise RuntimeError("published output contains the excluded substring")
    return output, len(source_lines), removed_count, source_sha256


def sync(mirror: Mirror, check: bool) -> None:
    output, source_count, removed_count, source_sha256 = render(
        mirror,
        fetch_upstream(mirror.upstream_url),
    )
    if check:
        if not mirror.output.exists():
            raise RuntimeError(f"missing generated artifact: {mirror.output}")
        if mirror.output.read_text(encoding="utf-8") != output:
            raise RuntimeError(
                f"generated artifact is stale: {mirror.output.relative_to(ROOT)}; "
                "run scripts/sync_qx_adblock.py"
            )
        action = "verified"
    else:
        mirror.output.parent.mkdir(parents=True, exist_ok=True)
        mirror.output.write_text(output, encoding="utf-8")
        action = "wrote"
    print(
        f"{action} {mirror.output.relative_to(ROOT)}: source_lines={source_count} "
        f"omitted={removed_count} upstream_sha256={source_sha256}"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that every committed artifact matches the current upstream transform",
    )
    args = parser.parse_args()
    for mirror in MIRRORS:
        sync(mirror, args.check)


if __name__ == "__main__":
    try:
        main()
    except (OSError, UnicodeError, RuntimeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
